'/static/imgs/drivers/Albon.jpeg'
'/static/imgs/drivers/Alonso.jpeg'
'/static/imgs/drivers/Bottas.jpeg'
'/static/imgs/drivers/Gasly.jpeg'
'/static/imgs/drivers/Guanyu.jpeg'
'/static/imgs/drivers/Hamilton.jpeg'
'/static/imgs/drivers/Latifi.jpeg'
'/static/imgs/drivers/Leclerc.jpeg'
'/static/imgs/drivers/Magnessun.jpeg'
'/static/imgs/drivers/Norris.jpeg'
'/static/imgs/drivers/Ocon.jpeg'
'/static/imgs/drivers/Perez.jpeg'
'/static/imgs/drivers/Ricardo.jpeg'
'/static/imgs/drivers/Russel.jpeg'
'/static/imgs/drivers/Sainz.jpeg'
'/static/imgs/drivers/Schumaker.jpeg'
'/static/imgs/drivers/Stroll.jpeg'
'/static/imgs/drivers/Tsuonada.jpeg'
'/static/imgs/drivers/Verstappen.jpeg'
'/static/imgs/drivers/Vettel.jpeg'



